- name: Update pacman packages
  become: true
  pacman:
    state: latest
    update_cache: yes
    upgrade: yes

- name: Install adw-gtk3 theme
  kewlfft.aur.aur:
    use: paru
    name: adw-gtk3

- name: Install gnome-tweaks
  kewlfft.aur.aur:
    use: paru
    name: gnome-tweaks

- name: Install firefox
  kewlfft.aur.aur:
    use: paru
    name: firefox

- name: Install visual studio code
  kewlfft.aur.aur:
    use: paru
    name: visual-studio-code-bin
  
- name: Install lazygit
  kewlfft.aur.aur:
    use: paru
    name: lazygit

- name: Install hyprland & dependencies
  kewlfft.aur.aur:
    use: paru
    name:
      - hyprland-git
      - aylurs-gtk-shell
      - rofi-wayland
      - playerctl
      - openssl
      - network-manager-applet
      - kitty
      - xdg-utils
      - xdg-user-dirs
      - python-requests
      - python-pip
      - curl
      - swaync
      - swayidle
      - wl-clipboard
      - wlogout
      - yad
      - swappy
      - slurp
      - qt6ct
      - qt5ct
      - qt6-svg
      - pamixer
      - pavucontrol
      - pipewire-alsa
      - xdg-desktop-portal-hyprland

- name: Install zsh
  kewlfft.aur.aur:
    use: paru
    name: 
      - zsh
      - util-linux