- name: Enabling multilib
  become: true
  blockinfile:
    path: /etc/pacman.conf
    block: |
        [multilib]
        Include = /etc/pacman.d/mirrorlist
    state: present

- name: Update pacman packages
  become: true
  pacman:
    state: latest
    update_cache: yes
    upgrade: yes

- name: Install adw-gtk3 theme
  kewlfft.aur.aur:
    use: paru
    name: adw-gtk3

- name: Install gnome-tweaks
  kewlfft.aur.aur:
    use: paru
    name: gnome-tweaks

- name: Install firefox
  kewlfft.aur.aur:
    use: paru
    name: firefox

- name: Install visual studio code
  kewlfft.aur.aur:
    use: paru
    name: visual-studio-code-bin
  
- name: Install lazygit
  kewlfft.aur.aur:
    use: paru
    name: lazygit

- name: Install hyprland & dependencies
  kewlfft.aur.aur:
    use: paru
    name:
      - hyprland-git
      - aylurs-gtk-shell
      - rofi-wayland
      - playerctl
      - openssl
      - network-manager-applet
      - kitty
      - xdg-utils
      - xdg-user-dirs
      - python-requests
      - python-pip
      - curl
      - swaync
      - swayidle
      - wl-clipboard
      - wlogout
      - yad
      - swappy
      - slurp
      - qt6ct
      - qt5ct
      - qt6-svg
      - pamixer
      - pavucontrol
      - pipewire-alsa
      - xdg-desktop-portal-hyprland
      - flameshoto

- name: Install blackbox
  kewlfft.aur.aur:
    use: paru
    name:
      - blackbox-terminal
      - nautilus-open-in-blackbox

- name: Install zsh
  kewlfft.aur.aur:
    use: paru
    name: 
      - zsh
      - util-linux
      - krabby-bin
      - ttf-jetbrains-mono-nerd

- name: Install starship
  kewlfft.aur.aur:
    use: paru
    name: starship

- name: Check if nvm is installed
  shell: command -v nvm 
  register: nvm_exists
  ignore_errors: true

- name: Install nvm
  when: nvm_exists is failed
  shell: wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash

- name: Install rust
  kewlfft.aur.aur:
    use: paru
    name: rustup

- name: Check if bun is installed
  shell: command -v bun
  register: bun_exists
  ignore_errors: true

- name: Install bun
  when: bun_exists is failed
  shell: curl -fsSL https://bun.sh/install | bash
  tags:
    - bun

- name: Install build tools
  kewlfft.aur.aur:
    use: paru
    name: base-devel

- name: Install jetbrains toolbox
  kewlfft.aur.aur:
    use: paru
    name: jetbrains-toolbox

- name: Install steam
  kewlfft.aur.aur:
    use: paru
    name: steam

- name: Install spotify
  kewlfft.aur.aur:
    use: paru
    name: spotify

- name: Install docker
  kewlfft.aur.aur:
    use: paru
    name: docker

- name: Create "docker" group
  group:
    name: docker
    state: present

- name: Add user to "docker" group
  user:
    name: "{{ remote_user }}"
    group: "docker"
    append: yes

- name: Install kubernetes (tools)
  kewlfft.aur.aur:
    use: paru
    name:
      - kubectl
      - skaffold-bin
      - protobuf
      - k9s